version: "3"
services:
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Set environment variables if required
      MONGO_URL: "mongodb://database:27017"
    depends_on:
      - database

  # Mongo DB Container
  database:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  # NGINX Container
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro 
    ports:
      - "5050:80"
    depends_on:
      - server

volumes:
  mongo_db: {}
